{{- include "prometheus-postgres-exporter.validateValues" . }}
{{- if and .Values.config.datasourceSecret.csi }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prometheus-postgres-exporter.fullname" . }}
    driver: csi-secrets-store
    provider: aws
spec:
{{ toYaml .Values.config.datasourceSecret.csi.secretProviderClass | indent 2 }}
{{- end }}
