{{- include "prometheus-postgres-exporter.validateValues" . -}}
{{- if .Values.config.datasource.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  data_source_password: {{ tpl (.Values.config.datasource.password | default "somepaswword") . | b64enc }}
{{- end -}}