mappings:
- match: "^([-a-zA-Z0-9]+).([-a-zA-Z0-9]+).(.+).counter$"
  match_metric_type: counter
  match_type: "regex"
  name: "${3}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$1"
    environment: "$2"
- match: "^([-a-zA-Z0-9]+).([-a-zA-Z0-9]+).(.+).timer$"
  match_metric_type: timer
  match_type: "regex"
  name: "${3}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$1"
    environment: "$2"
- match: "^([-a-zA-Z0-9]+).([-a-zA-Z0-9]+).(.+).gauge$"
  match_metric_type: gauge
  match_type: "regex"
  name: "${3}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$1"
    environment: "$2"