mappings:
- match: "^([a-zA-Z-]+).([a-zA-Z-]+).([-a-zA-Z0-9_-]+).([a-zA-Z_-]+).counter$"
  match_metric_type: counter
  match_type: "regex"
  name: "${2}_${4}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$3"
    environment: "$1"
    component: "$2"
- match: "^([a-zA-Z-]+).([a-zA-Z-]+).([-a-zA-Z0-9_-]+).([a-zA-Z_-]+).timer$"
  match_metric_type: timer
  match_type: "regex"
  name: "${2}_${4}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$3"
    environment: "$1"
    component: "$2"
- match: "^([a-zA-Z-]+).([a-zA-Z-]+).([-a-zA-Z0-9_-]+).([a-zA-Z_-]+).gauge$"
  match_metric_type: gauge
  match_type: "regex"
  name: "${2}_${4}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$3"
    environment: "$1"
    component: "$2"