mappings:
- match: "^([^.]+)\\.([^.]+)\\.(.+)\\.(counter|timer|gauge)$"
  match_metric_type: "$4"
  match_type: "regex"
  name: "${3}"
  help: "Custom application metrics from microservices"
  labels:
    pod_id: "$1"
    environment: "$2"
    type: "$4"
