#!/bin/bash

set -eo pipefail

scripts/format.sh
scripts/generate-readme.sh

# change directory to where your terraform files are
cd path/to/terraform/files

echo "Running Terraform Init..."
terraform init -backend=false

echo "Running Terraform Validate..."
terraform validate

# Cleanup after validation
rm -rf .terraform
rm -f .terraform.lock.hcl
